import type { Lead, Application } from "@/lib/crm-types";

export const MOCK_LEADS: Lead[] = [
  {
    id: "mock-1",
    reference_id: "PAM-000001",
    category: "Bulk Fuel Supply (Oil & Gas)",
    routing_tag: "bulk_fuel_supply",
    status: "new",
    priority: "high",
    name: "Chief Emeka Okafor",
    email: "emeka.okafor@oilco.ng",
    phone: "+234 803 000 1111",
    organization: "Oilco Nigeria Ltd",
    message:
      "We require 50,000 liters of AGO delivered weekly to our Enugu plant. Please send pricing and SLA.",
    notes: null,
    assigned_to: null,
    source: "contact_page",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-2",
    reference_id: "PAM-000002",
    category: "Autoland Service & Fleet Repairs",
    routing_tag: "autoland_service",
    status: "contacted",
    priority: "medium",
    name: "Mrs Ngozi Adeyemi",
    email: "ngozi.adeyemi@gmail.com",
    phone: "+234 805 200 3344",
    organization: null,
    message:
      "I have a Toyota Prado that needs full suspension overhaul and ECU diagnostics. How soon can I schedule?",
    notes: "Called back. Scheduled for Friday 9am.",
    assigned_to: "Chukwudi Eze",
    source: "business_line_cta",
    created_at: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-3",
    reference_id: "PAM-000003",
    category: "Real Estate & Property Investment",
    routing_tag: "real_estate_investment",
    status: "qualified",
    priority: "high",
    name: "Dr. Chibuike Nwosu",
    email: "cnwosu@nwosufamily.com",
    phone: "+234 808 456 7890",
    organization: "Nwosu Family Office",
    message:
      "Interested in purchasing 2 units at 08 City Garden as rental investment. Would like to discuss payment plan.",
    notes: "Sent brochure. Very serious buyer. Follow up Monday.",
    assigned_to: "Adaeze Obiora",
    source: "business_line_cta",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-4",
    reference_id: "PAM-000004",
    category: "Luxury Ride & VIP Chauffeur Booking",
    routing_tag: "luxury_ride_reservation",
    status: "converted",
    priority: "high",
    name: "Alhaji Musa Garba",
    email: "agarba@statelodge.gov.ng",
    phone: "+234 802 111 2233",
    organization: "Imo State Lodge",
    message:
      "We need a 5-vehicle executive convoy for a 3-day state function next month. Please quote full package.",
    notes: "Booking confirmed. Invoice sent. Deposit received.",
    assigned_to: "Chukwudi Eze",
    source: "inquiry_modal",
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-5",
    reference_id: "PAM-000005",
    category: "Media & Creative Advertising",
    routing_tag: "media___advertising",
    status: "new",
    priority: "low",
    name: "Tolu Bankole",
    email: "tolu@brandcraft.com.ng",
    phone: "+234 901 333 5566",
    organization: "BrandCraft Agency",
    message:
      "Looking to produce a 4-minute corporate documentary for our annual report. Do you handle full production?",
    notes: null,
    assigned_to: null,
    source: "contact_page",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "app-mock-1",
    job_id: "job-001",
    job_title: "Senior Full-Stack Engineer",
    department: "Technology",
    location: "Port Harcourt",
    status: "shortlisted",
    name: "Adaora Obi",
    email: "adaora.obi@techmail.ng",
    phone: "+234 804 555 7788",
    linkedin_url: "https://linkedin.com/in/adaora-obi",
    pitch:
      "I have 6 years building scalable fintech platforms across Nigeria and Ghana. Deeply passionate about solving infrastructure problems with clean code.",
    resume_url: null,
    resume_filename: "Adaora_Obi_CV_2026.pdf",
    notes: "Strong portfolio. Schedule technical interview.",
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "app-mock-2",
    job_id: "job-003",
    job_title: "Fleet Operations Manager",
    department: "Logistics & Fleet",
    location: "Owerri",
    status: "received",
    name: "Emeka Chukwu",
    email: "emeka.chukwu@gmail.com",
    phone: "+234 806 123 4567",
    linkedin_url: null,
    pitch:
      "15 years in fleet management for multinational logistics firms. Available immediately.",
    resume_url: null,
    resume_filename: "Emeka_Chukwu_Resume.pdf",
    notes: null,
    created_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "app-mock-3",
    job_id: "job-002",
    job_title: "Brand & Marketing Lead",
    department: "Marketing",
    location: "Lagos",
    status: "interviewed",
    name: "Zainab Aliyu",
    email: "zainab.aliyu@markethub.co",
    phone: "+234 803 999 0011",
    linkedin_url: "https://linkedin.com/in/zainab-aliyu",
    pitch:
      "Led brand strategy at 3 top Nigerian consumer brands. Expert in digital-first campaigns and storytelling.",
    resume_url: null,
    resume_filename: "Zainab_Aliyu_Portfolio.pdf",
    notes: "Excellent communication. Salary expectation above band — negotiate.",
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
